apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcapp
  namespace: default
  labels:
    app: wcapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wcapp
  template:
    metadata:
      labels:
        app: wcapp
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: wcapp
        image: wcapp
        imagePullPolicy: Never
        ports:
        - containerPort: 443
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1536M
          requests:
            cpu: 100m
            memory: 512M
        securityContext:
          runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: wcapp
  namespace: default
  labels:
    app: wcapp
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  selector:
    app: wcapp