apiVersion: apps/v1
kind: Deployment
metadata:
  name: sock
  namespace: default
  labels:
    app: sock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sock
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: sock
        namespace: default
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sock
        image: wcsock
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 400M
          requests:
            cpu: 25m
            memory: 100M
---
apiVersion: v1
kind: Service
metadata:
  name: sock
  namespace: default
  labels:
    app: sock
spec:
  ports:
  - name: sock
    port: 8081
    targetPort: 8080
  selector:
    app: sock
    release: {{ .Release.Name }}
