apiVersion: apps/v1
kind: Deployment
metadata:
  name: turn
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turn
  template:
    metadata:
      labels:
        app: turn
        namespace: application
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: turn
        image: wcturn
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3478
        resources:
          limits:
            cpu: 250m
            memory: 768M
          requests:
            cpu: 100m
            memory: 512M
        securityContext:
          runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: turn
  namespace: application
  labels:
    app: turn
spec:
  ports:
  - name: turn
    port: 3478
    targetPort: 3478
  selector:
    app: turn
    release: {{ .Release.Name }}
