apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: graylog-secrets
  namespace: default
spec:
  encryptedData:
    GRAYLOG_PASSWORD_SECRET: AgAAANIS5880l0bpUMKsORIqKSWY5cA4N5P/mKT3e6sEuYq/BCyJf+dLQEihCjxgRxkAIwGsHL5KLbz2dRTWSs8KHa5YouNXScOTzgtx5B//H8UVogmv89z2bBp1u0UanLhQAnx08mo5zbrbSlIlur3nsVy8jlAVsNMLzO8qVxIgYm+YJV2m8y3+vsttG8BuyFIROJT+iAy+znduEXMjdO7UwxpHyy/NttGt96taOj2csrt4lTpMP2FWFZ2gyzPQaQUBvdyfgADGUOcrvNl3AtU2EMGrGCuur4OjEyppFmqSLoj1SJe1MtiJKhGET0MCGQR9ArqL0IJNAkwox9Y0OzRV1OirFAGCrOGaiTt2zZkQBJAOgYPngR4t0Xb+vcyJDarROjaZiAFc21flR2D6DeNvguffwa7oT5b5pPzikkBcDf5GkJd4ykwDNmJdmBLwcbRq0Wbw849WUtaKakIF5vMT6X5x+O4867s8BEc4uCDp7AkAgiAq6T6RP1HiiFeFQonMGhPa1mUncf5/SbP0GQ85jOMOT0bV6alCCZnbiO+Z1gyLS1/r2WZjfOivXJN8iq3VEX+pseiyj0BgPEtjzuPhsOoxgp9BqxRlCJfLE1xMe6/jDHEhJ2VTGYp3eXvBErbvnLcrmQnZzUal0V3HCjPzrd0Wy280JX1PKkkhqyQhp3f3EWk+AIFcnRjwLhJVMtnd1b9iUPeO4z/nhH3uFtNBSWyY37ep
    GRAYLOG_ROOT_PASSWORD_SHA2: AgA0HJHyFabu/gGrDd3ujzLKpfSe54CUuyOMYzRcwvARA8p9ZLdDuKZr5npZ/k79d80ekkES0+I6ZZ2rsjV5kqX+1EnLVaPRgpdpYEGQR5sVp1DdMC9/l+DukyUI8bnQXBr0i4C4QgnBi8Baw5+vk3fxy2Bw6kOrCE98vBXAj/4d5/i8yhW1iQ8LCjUZbBFOSzfbOMcYH9729gjdJ+0xmTvc7nMkK6WIP4HsBuOZ5HXzOQw3uhokm+EkCq/pSdYBaxE/FBqtlIZARg9lYQL4bOKsMDQiXsI75KM0z+klRGUp9nESoCdQsHYISgkLX+QcyVPapykoq5/rQqlstku1yyUMi9Opcp6g/BEfUzUWF0vM1aZv4fIWv/DkRFhoEzrUAp6Eq2qsyGEV87BwNr0JSG0Hy6+WASKXHRCF7e5DPV7hlxD7o9dyzYfCabIzWktaofiLWmQ/C3UYfhw5i8EYTzK9Ef0UsrV6sr4belI0GoFVbQqJeKRGbEHzMCMrJ8lIZ7Orgg1HnUhcCbqeAj99ybOYH1VTaosO/2PvUSQxFGn1at/zfI5KZ9jKVMbWvWsgt7dFrmOK8c7oySVg8DUY52ZnZpoV3RJl0FjtHgkiutOdw7YivHSEhmV1nX/5nT0h/aIp/lnCvzIfZ2LwFJHbouIKVXGW7jrp3OyEfczyrU0Ewk/RUA2oDc3hBB3UmgfHpVf04u6xHMZSHmM28zQWPHl1EOjqItHQVMVbNUzj7i9i0YVBYmRH+QuAhEEBX/q5oKgo3Pt4k8gwEzxK29HdXHvh
  template:
    metadata:
      creationTimestamp: null
      name: graylog-secrets
      namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: graylog-cm
  namespace: default
data:
  GRAYLOG_HTTP_BIND_ADDRESS: 0.0.0.0:9000
  GRAYLOG_HTTP_EXTERNAL_URI: {{ .Values.graylog.endpoint }}
  GRAYLOG_SERVER_JAVA_OPTS: -Xms1g -Xmx1g -XX:NewRatio=1 -XX:MaxMetaspaceSize=256m -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: graylog
  namespace: default
  labels:
    app: graylog
    release: {{ .Release.Name }}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: graylog
      release: {{ .Release.Name }}
  template:
    metadata:
      namespace: default
      labels:
        app: graylog
        release: {{ .Release.Name }}
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: graylog-cm
        - secretRef:
            name: graylog-secrets
        image: graylog/graylog:3.0.1
        imagePullPolicy: IfNotPresent
        name: graylog-master
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        - containerPort: 12201
          name: udp-input
          protocol: TCP
        - containerPort: 1514
          name: tcp-input
          protocol: TCP
        readinessProbe:
          failureThreshold: 4
          httpGet:
            path: /api/system/lbstatus
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 1000m
            memory: 1500M
          requests:
            cpu: 100m
            memory: 512M
        securityContext:
          privileged: true
          runAsUser: 1100
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/graylog/data/journal
          name: graylog-persistent-storage
          subPath: graylog
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - chown -R 1100:1100 /usr/share/graylog/data/journal
        - chmod 777 /usr/share/graylog/data/journal/graylog2-committed-read-offset
        - chmod g+rwx /usr/share/graylog/data/journal/graylog2-committed-read-offset
        - chgrp 1100 /usr/share/graylog/data/journal/graylog2-committed-read-offset
        - chown -R 1100:1100 ./graylog_journal
        - chown -R 1100:1100 /usr/share/graylog/data/journal
        - chown -R 1100:1100 /usr/share/graylog/data/journal/graylog2-committed-read-offset
        image: busybox:1.29.2
        imagePullPolicy: IfNotPresent
        name: set-dir-owner
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/graylog/data/journal
          name: graylog-persistent-storage
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 70
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      name: graylog-persistent-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: graylog-lb
#   namespace: default
#   labels:
#     app: graylog
#     release: {{ .Release.Name }}
# spec:
#   type: LoadBalancer
#   ports:
#   selector:
#     app: graylog
#     release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: default
  labels:
    app: graylog
    release: {{ .Release.Name }}
spec:
  ports:
  - name: tcp-9000
    protocol: TCP
    port: 80
    targetPort: 9000
  - name: tcp-514
    protocol: TCP
    port: 514
    targetPort: 514
  - name: tcp-12201
    protocol: TCP
    port: 12201
    targetPort: 12201
  - name: udp-514
    protocol: UDP
    port: 514
    targetPort: 514
  - name: udp-12201
    protocol: UDP
    port: 12201
    targetPort: 12201
  selector:
    app: graylog
    release: {{ .Release.Name }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graylog
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: logs.local
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: graylog
            port:
              number: 80